### ISSUE TITLE
Serial port exception with tracer

### ISSUE THREAD

**Issue by retrodaredevil** [wildmountainfarms/solarthing#39]
Here's an issue for me to fix later:

```
2021-07-19 22:29:39.156 [main] INFO  me.retrodaredevil.solarthing.program.SolarMain - [LOG] Beginning main. Jar: solarthing-2021.6.0.jar Java version: 11.0.11
2021-07-19 22:29:47.195 [main] INFO  me.retrodaredevil.solarthing.program.RequestMain - Beginning request program
2021-07-19 22:29:47.224 [main] INFO  me.retrodaredevil.solarthing.analytics.AnalyticsManager - Google Analytics is disabled
2021-07-19 22:29:53.839 [main] INFO  me.retrodaredevil.solarthing.program.PacketHandlerInit - Commands are disabled
2021-07-19 22:29:54.355 [main] ERROR me.retrodaredevil.solarthing.program.SolarMain - [LOG] Ending SolarThing. Jar: solarthing-2021.6.0.jar Java version: 11.0.11
2021-07-19 22:29:54.358 [main] ERROR me.retrodaredevil.solarthing.program.SolarMain - (Fatal)Got throwable
java.lang.UnsatisfiedLinkError: 'long com.fazecast.jSerialComm.SerialPort.openPortNative()'
	at com.fazecast.jSerialComm.SerialPort.openPortNative(Native Method) ~[solarthing-2021.6.0.jar:?]
	at com.fazecast.jSerialComm.SerialPort.openPort(SerialPort.java:448) ~[solarthing-2021.6.0.jar:?]
	at me.retrodaredevil.io.serial.JSerialIOBundle.<init>(JSerialIOBundle.java:21) ~[solarthing-2021.6.0.jar:?]
	at me.retrodaredevil.solarthing.config.io.SerialIOConfig.createIOBundle(SerialIOConfig.java:46) ~[solarthing-2021.6.0.jar:?]
	at me.retrodaredevil.solarthing.io.ReloadableIOBundle.reload(ReloadableIOBundle.java:55) ~[solarthing-2021.6.0.jar:?]
	at me.retrodaredevil.solarthing.io.ReloadableIOBundle.<init>(ReloadableIOBundle.java:30) ~[solarthing-2021.6.0.jar:?]
	at me.retrodaredevil.solarthing.config.request.modbus.ModbusDataRequester.create(ModbusDataRequester.java:43) ~[solarthing-2021.6.0.jar:?]
	at me.retrodaredevil.solarthing.program.RequestMain.startRequestProgram(RequestMain.java:54) ~[solarthing-2021.6.0.jar:?]
	at me.retrodaredevil.solarthing.program.RequestMain.startRequestProgram(RequestMain.java:39) ~[solarthing-2021.6.0.jar:?]
	at me.retrodaredevil.solarthing.program.SolarMain.doMainCommand(SolarMain.java:128) [solarthing-2021.6.0.jar:?]
	at me.retrodaredevil.solarthing.program.SolarMain.doMain(SolarMain.java:170) [solarthing-2021.6.0.jar:?]
	at me.retrodaredevil.solarthing.program.SolarMain.main(SolarMain.java:209) [solarthing-2021.6.0.jar:?]
```

**Comment by retrodaredevil** [comment]
Closing this since I haven't seen this pop up again. I believe this first popped up when I restarted an RPi. Hopefully we don't see this again and it's just a fluke.
