### ISSUE TITLE
Tracer IO Not reloading

### ISSUE THREAD

**Issue by retrodaredevil** [wildmountainfarms/solarthing#42]
Error for me to fix
```
2021-09-20 06:50:17.320 [main] ERROR me.retrodaredevil.solarthing.program.ModbusListUpdaterWrapper - Modbus exception
me.retrodaredevil.io.modbus.ModbusIORuntimeException: Got exception while writing
	at me.retrodaredevil.io.modbus.RtuDataEncoder.sendMessage(RtuDataEncoder.java:36) ~[solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.io.modbus.IOModbusSlaveBus.sendRequestMessage(IOModbusSlaveBus.java:25) ~[solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.io.modbus.ImmutableAddressModbusSlave.sendRequestMessage(ImmutableAddressModbusSlave.java:14) ~[solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.io.modbus.ModbusSlave.sendRequestMessage(ModbusSlave.java:24) ~[solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.solarthing.program.modbus.ModbusCacheSlave.cache(ModbusCacheSlave.java:38) ~[solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.solarthing.program.modbus.ModbusCacheSlave.cacheInput(ModbusCacheSlave.java:54) ~[solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.solarthing.program.modbus.ModbusCacheSlave.cacheInputRangeInclusive(ModbusCacheSlave.java:57) ~[solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.solarthing.config.request.modbus.TracerModbusRequester.cacheRegisters(TracerModbusRequester.java:70) ~[solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.solarthing.config.request.modbus.TracerModbusRequester.lambda$create$0(TracerModbusRequester.java:99) ~[solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.solarthing.program.ModbusListUpdaterWrapper.receive(ModbusListUpdaterWrapper.java:58) [solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.solarthing.packets.handling.PacketListReceiverMultiplexer.receive(PacketListReceiverMultiplexer.java:21) [solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.solarthing.packets.handling.PacketListReceiverMultiplexer.receive(PacketListReceiverMultiplexer.java:21) [solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.solarthing.program.RequestMain.doRequest(RequestMain.java:73) [solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.solarthing.program.RequestMain.startRequestProgram(RequestMain.java:67) [solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.solarthing.program.RequestMain.startRequestProgram(RequestMain.java:39) [solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.solarthing.program.SolarMain.doMainCommand(SolarMain.java:125) [solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.solarthing.program.SolarMain.doMain(SolarMain.java:167) [solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.solarthing.program.SolarMain.main(SolarMain.java:206) [solarthing-SNAPSHOT.jar:?]
Caused by: me.retrodaredevil.solarthing.io.NotInitializedIOException: IO not initialized!
	at me.retrodaredevil.solarthing.io.ReloadableIOBundle$2.write(ReloadableIOBundle.java:22) ~[solarthing-SNAPSHOT.jar:?]
	at java.io.OutputStream.write(OutputStream.java:157) ~[?:?]
	at java.io.OutputStream.write(OutputStream.java:122) ~[?:?]
	at me.retrodaredevil.solarthing.io.ReloadableIOBundle$4.write(ReloadableIOBundle.java:115) ~[solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.io.modbus.RtuDataEncoder.sendMessage(RtuDataEncoder.java:33) ~[solarthing-SNAPSHOT.jar:?]
	... 17 more
2021-09-20 06:50:17.524 [main] ERROR me.retrodaredevil.solarthing.io.ReloadableIOBundle - Could not create IOBundle
me.retrodaredevil.io.serial.SerialPortException: Was unsuccessful while trying to open port: ttyXRUSB0 descriptive name: User-Specified Port description: User-Specified Port
	at me.retrodaredevil.io.serial.JSerialIOBundle.<init>(JSerialIOBundle.java:22) ~[solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.solarthing.config.io.SerialIOConfig.createIOBundle(SerialIOConfig.java:46) ~[solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.solarthing.io.ReloadableIOBundle.reload(ReloadableIOBundle.java:55) ~[solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.solarthing.config.request.modbus.ReloadIOSuccessReporterHandler.doReload(ReloadIOSuccessReporterHandler.java:28) [solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.solarthing.config.request.modbus.ReloadIOSuccessReporterHandler.access$200(ReloadIOSuccessReporterHandler.java:11) [solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.solarthing.config.request.modbus.ReloadIOSuccessReporterHandler$UniqueReporter.reportTimeout(ReloadIOSuccessReporterHandler.java:47) [solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.solarthing.program.ModbusListUpdaterWrapper.receive(ModbusListUpdaterWrapper.java:97) [solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.solarthing.packets.handling.PacketListReceiverMultiplexer.receive(PacketListReceiverMultiplexer.java:21) [solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.solarthing.packets.handling.PacketListReceiverMultiplexer.receive(PacketListReceiverMultiplexer.java:21) [solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.solarthing.program.RequestMain.doRequest(RequestMain.java:73) [solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.solarthing.program.RequestMain.startRequestProgram(RequestMain.java:67) [solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.solarthing.program.RequestMain.startRequestProgram(RequestMain.java:39) [solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.solarthing.program.SolarMain.doMainCommand(SolarMain.java:125) [solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.solarthing.program.SolarMain.doMain(SolarMain.java:167) [solarthing-SNAPSHOT.jar:?]
	at me.retrodaredevil.solarthing.program.SolarMain.main(SolarMain.java:206) [solarthing-SNAPSHOT.jar:?]
```

**Comment by retrodaredevil** [comment]
I believe this occurred after updating the pi then restarting the pi.
Installing the serial driver again should fix it. Also worth noting that this error occurs when reinstalling:

```
joshua@batterypi:/opt/solarthing/other/linux $ sudo ./install_updated_serial_driver.sh 
[sudo] password for joshua: 
This will edit config files on your system to disable cdc-acm 
Only run this script if you need RS485 support for your EPEver tracer. DO NOT RUN OTHERWISE. THIS DOES NOT MAGICALLY FIX YOUR CABLE NOT WORKING.

fatal: destination path 'epsolar-tracer' already exists and is not an empty directory.
```
