### ISSUE TITLE
CouchDB timeout in PVOutput program

### ISSUE THREAD

**Issue by retrodaredevil** [wildmountainfarms/solarthing#43]
Here's the stacktrace:

```
2021-10-11 19:59:30.385 [main] DEBUG me.retrodaredevil.solarthing.program.pvoutput.PVOutputUploadMain - Going to do stuff now.
2021-10-11 19:59:43.507 [main] ERROR me.retrodaredevil.solarthing.program.pvoutput.PVOutputUploadMain - Couldn't get status packets
me.retrodaredevil.solarthing.database.exception.SolarThingDatabaseException: me.retrodaredevil.couchdbjava.exception.CouchDbException: Connection failed!
	at me.retrodaredevil.solarthing.database.couchdb.CouchDbMillisDatabase.query(CouchDbMillisDatabase.java:45) ~[solarthing-2021.6.1.jar:?]
	at me.retrodaredevil.solarthing.program.pvoutput.PVOutputUploadMain.startRealTimeProgram(PVOutputUploadMain.java:271) [solarthing-2021.6.1.jar:?]
	at me.retrodaredevil.solarthing.program.pvoutput.PVOutputUploadMain.startPVOutputUpload(PVOutputUploadMain.java:101) [solarthing-2021.6.1.jar:?]
	at me.retrodaredevil.solarthing.program.SolarMain.doMainCommand(SolarMain.java:126) [solarthing-2021.6.1.jar:?]
	at me.retrodaredevil.solarthing.program.SolarMain.doMain(SolarMain.java:170) [solarthing-2021.6.1.jar:?]
	at me.retrodaredevil.solarthing.program.SolarMain.main(SolarMain.java:209) [solarthing-2021.6.1.jar:?]
Caused by: me.retrodaredevil.couchdbjava.exception.CouchDbException: Connection failed!
	at me.retrodaredevil.couchdbjava.okhttp.OkHttpCouchDbInstance.executeCall(OkHttpCouchDbInstance.java:105) ~[solarthing-2021.6.1.jar:?]
	at me.retrodaredevil.couchdbjava.okhttp.OkHttpCouchDbInstance.executeAndHandle(OkHttpCouchDbInstance.java:94) ~[solarthing-2021.6.1.jar:?]
	at me.retrodaredevil.couchdbjava.okhttp.OkHttpCouchDbDatabase.queryView(OkHttpCouchDbDatabase.java:235) ~[solarthing-2021.6.1.jar:?]
	at me.retrodaredevil.solarthing.database.couchdb.CouchDbMillisDatabase.query(CouchDbMillisDatabase.java:43) ~[solarthing-2021.6.1.jar:?]
	... 5 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: timeout (through reference chain: me.retrodaredevil.couchdbjava.response.ViewResponse["rows"]->java.util.ArrayList[72])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:390) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:371) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:565) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:449) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2033) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1458) ~[solarthing-2021.6.1.jar:?]
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:33) ~[solarthing-2021.6.1.jar:?]
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23) ~[solarthing-2021.6.1.jar:?]
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243) ~[solarthing-2021.6.1.jar:?]
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204) ~[solarthing-2021.6.1.jar:?]
	at me.retrodaredevil.couchdbjava.okhttp.OkHttpCouchDbInstance.executeCall(OkHttpCouchDbInstance.java:103) ~[solarthing-2021.6.1.jar:?]
	at me.retrodaredevil.couchdbjava.okhttp.OkHttpCouchDbInstance.executeAndHandle(OkHttpCouchDbInstance.java:94) ~[solarthing-2021.6.1.jar:?]
	at me.retrodaredevil.couchdbjava.okhttp.OkHttpCouchDbDatabase.queryView(OkHttpCouchDbDatabase.java:235) ~[solarthing-2021.6.1.jar:?]
	at me.retrodaredevil.solarthing.database.couchdb.CouchDbMillisDatabase.query(CouchDbMillisDatabase.java:43) ~[solarthing-2021.6.1.jar:?]
	... 5 more
Caused by: java.io.InterruptedIOException: timeout
	at okhttp3.internal.connection.RealCall.timeoutExit(RealCall.kt:398) ~[solarthing-2021.6.1.jar:?]
	at okhttp3.internal.connection.RealCall.callDone(RealCall.kt:360) ~[solarthing-2021.6.1.jar:?]
	at okhttp3.internal.connection.RealCall.messageDone$okhttp(RealCall.kt:309) ~[solarthing-2021.6.1.jar:?]
	at okhttp3.internal.connection.Exchange.bodyComplete(Exchange.kt:193) ~[solarthing-2021.6.1.jar:?]
	at okhttp3.internal.connection.Exchange$ResponseBodySource.complete(Exchange.kt:324) ~[solarthing-2021.6.1.jar:?]
	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:300) ~[solarthing-2021.6.1.jar:?]
	at okio.RealBufferedSource.read(RealBufferedSource.kt:189) ~[solarthing-2021.6.1.jar:?]
	at okio.ForwardingSource.read(ForwardingSource.kt:29) ~[solarthing-2021.6.1.jar:?]
	at retrofit2.OkHttpCall$ExceptionCatchingResponseBody$1.read(OkHttpCall.java:314) ~[solarthing-2021.6.1.jar:?]
	at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158) ~[solarthing-2021.6.1.jar:?]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) ~[?:?]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[?:?]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[?:?]
	at java.io.InputStreamReader.read(InputStreamReader.java:181) ~[?:?]
	at okhttp3.ResponseBody$BomAwareReader.read(ResponseBody.kt:211) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._loadMore(ReaderBasedJsonParser.java:255) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._parseName2(ReaderBasedJsonParser.java:1758) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._parseName(ReaderBasedJsonParser.java:1743) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:941) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:269) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:469) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObjectAtName(JsonNodeDeserializer.java:334) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeAny(JsonNodeDeserializer.java:556) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:74) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:16) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1398) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:565) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:449) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:565) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:449) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2033) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1458) ~[solarthing-2021.6.1.jar:?]
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:33) ~[solarthing-2021.6.1.jar:?]
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23) ~[solarthing-2021.6.1.jar:?]
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243) ~[solarthing-2021.6.1.jar:?]
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204) ~[solarthing-2021.6.1.jar:?]
	at me.retrodaredevil.couchdbjava.okhttp.OkHttpCouchDbInstance.executeCall(OkHttpCouchDbInstance.java:103) ~[solarthing-2021.6.1.jar:?]
	at me.retrodaredevil.couchdbjava.okhttp.OkHttpCouchDbInstance.executeAndHandle(OkHttpCouchDbInstance.java:94) ~[solarthing-2021.6.1.jar:?]
	at me.retrodaredevil.couchdbjava.okhttp.OkHttpCouchDbDatabase.queryView(OkHttpCouchDbDatabase.java:235) ~[solarthing-2021.6.1.jar:?]
	at me.retrodaredevil.solarthing.database.couchdb.CouchDbMillisDatabase.query(CouchDbMillisDatabase.java:43) ~[solarthing-2021.6.1.jar:?]
	... 5 more
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:?]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:115) ~[?:?]
	at java.net.SocketInputStream.read(SocketInputStream.java:168) ~[?:?]
	at java.net.SocketInputStream.read(SocketInputStream.java:140) ~[?:?]
	at okio.InputStreamSource.read(JvmOkio.kt:90) ~[solarthing-2021.6.1.jar:?]
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129) ~[solarthing-2021.6.1.jar:?]
	at okio.RealBufferedSource.read(RealBufferedSource.kt:189) ~[solarthing-2021.6.1.jar:?]
	at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.kt:331) ~[solarthing-2021.6.1.jar:?]
	at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.kt:412) ~[solarthing-2021.6.1.jar:?]
	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276) ~[solarthing-2021.6.1.jar:?]
	at okio.RealBufferedSource.read(RealBufferedSource.kt:189) ~[solarthing-2021.6.1.jar:?]
	at okio.ForwardingSource.read(ForwardingSource.kt:29) ~[solarthing-2021.6.1.jar:?]
	at retrofit2.OkHttpCall$ExceptionCatchingResponseBody$1.read(OkHttpCall.java:314) ~[solarthing-2021.6.1.jar:?]
	at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158) ~[solarthing-2021.6.1.jar:?]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) ~[?:?]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[?:?]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[?:?]
	at java.io.InputStreamReader.read(InputStreamReader.java:181) ~[?:?]
	at okhttp3.ResponseBody$BomAwareReader.read(ResponseBody.kt:211) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._loadMore(ReaderBasedJsonParser.java:255) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._parseName2(ReaderBasedJsonParser.java:1758) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._parseName(ReaderBasedJsonParser.java:1743) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:941) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:269) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:469) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObjectAtName(JsonNodeDeserializer.java:334) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeAny(JsonNodeDeserializer.java:556) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:74) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:16) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1398) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:565) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:449) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:565) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:449) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2033) ~[solarthing-2021.6.1.jar:?]
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1458) ~[solarthing-2021.6.1.jar:?]
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:33) ~[solarthing-2021.6.1.jar:?]
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23) ~[solarthing-2021.6.1.jar:?]
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243) ~[solarthing-2021.6.1.jar:?]
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204) ~[solarthing-2021.6.1.jar:?]
	at me.retrodaredevil.couchdbjava.okhttp.OkHttpCouchDbInstance.executeCall(OkHttpCouchDbInstance.java:103) ~[solarthing-2021.6.1.jar:?]
	at me.retrodaredevil.couchdbjava.okhttp.OkHttpCouchDbInstance.executeAndHandle(OkHttpCouchDbInstance.java:94) ~[solarthing-2021.6.1.jar:?]
	at me.retrodaredevil.couchdbjava.okhttp.OkHttpCouchDbDatabase.queryView(OkHttpCouchDbDatabase.java:235) ~[solarthing-2021.6.1.jar:?]
	at me.retrodaredevil.solarthing.database.couchdb.CouchDbMillisDatabase.query(CouchDbMillisDatabase.java:43) ~[solarthing-2021.6.1.jar:?]
	... 5 more
2021-10-11 19:59:45.520 [main] DEBUG me.retrodaredevil.solarthing.program.pvoutput.PVOutputUploadMain - Going to sleep now
```

**Comment by retrodaredevil** [comment]
This seemed to get fixed when I restarted the program. Maybe there's some hidden ClassDefNotFoundError that we don't have the stacktrace of.

Closing this now. Just wanted to document the stacktrace before I lose it.
