### ISSUE TITLE
Solcast Unknown Host

### ISSUE THREAD

**Issue by retrodaredevil** [wildmountainfarms/solarthing#46]
Here's an error I was getting the GraphQL program when it tried to get Solcast data
```
Oct 29 20:29:49 nasplex run.sh[624]: 2021-10-29 20:29:49.581  INFO 732 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
Oct 29 20:29:50 nasplex run.sh[624]: Didn't have to get any data
Oct 29 20:29:50 nasplex run.sh[624]: Going to retrieve forecasts from solcast!
Oct 29 20:30:00 nasplex run.sh[624]: Going to retrieve forecasts from solcast!
Oct 29 20:30:00 nasplex run.sh[624]: Going to retrieve forecasts from solcast!
Oct 29 20:30:00 nasplex run.sh[624]: 2021-10-29 20:30:00.927  WARN 732 --- [nio-8080-exec-4] n.g.e.SimpleDataFetcherExceptionHandler  : Exception while fetching data (/data/data) 
Oct 29 20:30:00 nasplex run.sh[624]: java.net.UnknownHostException: api.solcast.com.au
Oct 29 20:30:00 nasplex run.sh[624]:         at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797) ~[na:na]
Oct 29 20:30:00 nasplex run.sh[624]:         at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509) ~[na:na]
Oct 29 20:30:00 nasplex run.sh[624]:         at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368) ~[na:na]
Oct 29 20:30:00 nasplex run.sh[624]:         at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302) ~[na:na]
Oct 29 20:30:00 nasplex run.sh[624]:         at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49) ~[okhttp-4.9.1.jar!/:na]
Oct 29 20:30:00 nasplex run.sh[624]:         at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:164) ~[okhttp-4.9.1.jar!/:na]
Oct 29 20:30:00 nasplex run.sh[624]:         at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:129) ~[okhttp-4.9.1.jar!/:na]
Oct 29 20:30:00 nasplex run.sh[624]:         at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71) ~[okhttp-4.9.1.jar!/:na]
```

**Comment by retrodaredevil** [comment]
This fixes itself after it boots up. I think the problem I'm having is from #45 . This issue is unrelated and was never an issue in the first place.
