### ISSUE TITLE
WebSocketClient objects are not reuseable

### ISSUE THREAD

**Issue by retrodaredevil** [wildmountainfarms/solarthing#54]
Got this error today.
```
2022-05-08 13:14:18.094 [main] ERROR me.retrodaredevil.solarthing.program.SolarMain - [LOG] Ending SolarThing. Jar: solarthing-2022.2.0.jar Last Modified: 2022-02-27T07:18:51Z Java version: 11.0.15
2022-05-08 13:14:18.094 [main] ERROR me.retrodaredevil.solarthing.program.SolarMain - (Fatal)Got throwable
java.lang.IllegalStateException: WebSocketClient objects are not reuseable
        at org.java_websocket.client.WebSocketClient.connect(WebSocketClient.java:372) ~[solarthing-2022.2.0.jar:?]
        at com.slack.api.socket_mode.impl.SocketModeClientJavaWSImpl.connect(SocketModeClientJavaWSImpl.java:121) ~[solarthing-2022.2.0.jar:?]
        at me.retrodaredevil.solarthing.actions.chatbot.SlackChatBotAction.initClient(SlackChatBotAction.java:90) ~[solarthing-2022.2.0.jar:?]
        at me.retrodaredevil.solarthing.actions.chatbot.SlackChatBotAction.onUpdate(SlackChatBotAction.java:46) ~[solarthing-2022.2.0.jar:?]
        at me.retrodaredevil.action.SimpleAction.update(SimpleAction.java:66) ~[solarthing-2022.2.0.jar:?]
        at me.retrodaredevil.action.DequeActionQueue.updateAction(DequeActionQueue.java:154) ~[solarthing-2022.2.0.jar:?]
        at me.retrodaredevil.action.DequeActionQueue.onUpdate(DequeActionQueue.java:145) ~[solarthing-2022.2.0.jar:?]
        at me.retrodaredevil.action.SimpleAction.update(SimpleAction.java:66) ~[solarthing-2022.2.0.jar:?]
        at me.retrodaredevil.action.DefaultActionChooser.onUpdate(DefaultActionChooser.java:69) ~[solarthing-2022.2.0.jar:?]
        at me.retrodaredevil.action.SimpleAction.update(SimpleAction.java:66) ~[solarthing-2022.2.0.jar:?]
        at me.retrodaredevil.action.DynamicActionRunner.onUpdate(DynamicActionRunner.java:21) ~[solarthing-2022.2.0.jar:?]
        at me.retrodaredevil.action.SimpleAction.update(SimpleAction.java:66) ~[solarthing-2022.2.0.jar:?]
        at me.retrodaredevil.action.SetActionMultiplexer.onUpdate(SetActionMultiplexer.java:95) ~[solarthing-2022.2.0.jar:?]
        at me.retrodaredevil.action.SimpleAction.update(SimpleAction.java:66) ~[solarthing-2022.2.0.jar:?]
        at me.retrodaredevil.solarthing.program.AutomationMain.startAutomation(AutomationMain.java:154) ~[solarthing-2022.2.0.jar:?]
        at me.retrodaredevil.solarthing.program.AutomationMain.startAutomation(AutomationMain.java:57) ~[solarthing-2022.2.0.jar:?]
        at me.retrodaredevil.solarthing.program.SolarMain.doMainCommand(SolarMain.java:147) [solarthing-2022.2.0.jar:?]
        at me.retrodaredevil.solarthing.program.SolarMain.doMain(SolarMain.java:187) [solarthing-2022.2.0.jar:?]
        at me.retrodaredevil.solarthing.program.SolarMain.determineMainSubprogram(SolarMain.java:252) [solarthing-2022.2.0.jar:?]
        at me.retrodaredevil.solarthing.program.SolarMain.main(SolarMain.java:256) [solarthing-2022.2.0.jar:?]
```

**Comment by retrodaredevil** [comment]
I believe a9381820f3853039c72be2fe4b3c696c3e24c60a closes this
