### ISSUE TITLE
Immediate crash caused by UnsatisfiedLinkError loading libjSerialComm.so

### ISSUE THREAD

**Issue by retrodaredevil** [wildmountainfarms/solarthing#74]
Got this output

```
2022-10-31 01:30:41.048 [main] INFO  me.retrodaredevil.solarthing.program.SolarMain - [LOG] Beginning main. Jar: Jar: solarthing-2022.3.1.jar Last Modified: 2022-06-23T04:33:38Z Java version: 17.0.1
2022-10-31 01:30:48.690 [main] INFO  me.retrodaredevil.solarthing.program.RequestMain - Beginning request program
2022-10-31 01:30:48.700 [main] INFO  me.retrodaredevil.solarthing.analytics.AnalyticsManager - Google Analytics is disabled
2022-10-31 01:31:08.987 [main] INFO  me.retrodaredevil.solarthing.program.PacketHandlerInit - Command are enabled!
2022-10-31 01:31:09.851 [main] ERROR me.retrodaredevil.solarthing.program.SolarMain - [LOG] Ending SolarThing. Jar: solarthing-2022.3.1.jar Last Modified: 2022-06-23T04:33:38Z Java version: 17.0.1
2022-10-31 01:31:09.854 [main] ERROR me.retrodaredevil.solarthing.program.SolarMain - (Fatal)Got throwable
java.lang.UnsatisfiedLinkError: Can't load library: /tmp/jSerialComm/1667201469840-libjSerialComm.so
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393) ~[?:?]
	at java.lang.Runtime.load0(Runtime.java:755) ~[?:?]
	at java.lang.System.load(System.java:1953) ~[?:?]
	at com.fazecast.jSerialComm.SerialPort.<clinit>(SerialPort.java:248) ~[solarthing-2022.3.1.jar:?]
	at me.retrodaredevil.io.serial.JSerialIOBundle.createSerialPortFromName(JSerialIOBundle.java:77) ~[solarthing-2022.3.1.jar:?]
	at me.retrodaredevil.solarthing.config.io.SerialIOConfig.createIOBundle(SerialIOConfig.java:45) ~[solarthing-2022.3.1.jar:?]
	at me.retrodaredevil.solarthing.io.ReloadableIOBundle.reload(ReloadableIOBundle.java:55) ~[solarthing-2022.3.1.jar:?]
	at me.retrodaredevil.solarthing.io.ReloadableIOBundle.<init>(ReloadableIOBundle.java:30) ~[solarthing-2022.3.1.jar:?]
	at me.retrodaredevil.solarthing.config.request.modbus.ModbusDataRequester.create(ModbusDataRequester.java:51) ~[solarthing-2022.3.1.jar:?]
	at me.retrodaredevil.solarthing.program.RequestMain.startRequestProgram(RequestMain.java:55) ~[solarthing-2022.3.1.jar:?]
	at me.retrodaredevil.solarthing.program.RequestMain.startRequestProgram(RequestMain.java:40) ~[solarthing-2022.3.1.jar:?]
	at me.retrodaredevil.solarthing.program.SolarMain.doMainCommand(SolarMain.java:146) ~[solarthing-2022.3.1.jar:?]
	at me.retrodaredevil.solarthing.program.SolarMain.doMain(SolarMain.java:197) ~[solarthing-2022.3.1.jar:?]
	at me.retrodaredevil.solarthing.program.SolarMain.determineMainSubprogram(SolarMain.java:257) ~[solarthing-2022.3.1.jar:?]
	at me.retrodaredevil.solarthing.program.SolarMain.main(SolarMain.java:271) ~[solarthing-2022.3.1.jar:?]
```

Will have to investigate. For now, restarting was successful.

**Comment by retrodaredevil** [comment]
Also worth noting that this caused the android absorb timer to not work because it's being temperature compensated by the rover temperature. Might want to do something about that in the android app to possibly use tracer temperature if rover not available.
